language: node_js
node_js:
  - '0.10'
env:
  - NODE_ENV=test
before_script:
  - npm install
script:
  - npm test
  - ./node_modules/jshint/bin/jshint index.js
  - ./node_modules/jshint/bin/jshint lib/*.js
  - ./node_modules/jshint/bin/jshint test/*.js
after_failure:
  - ls -1 log
  - cat log/*
